---
- hosts: all
  gather_facts: true
  become: yes

  pre_tasks:
  
    # - name: Add iptables rule
    #   iptables:
    #     chain: INPUT
    #     protocol: udp
    #     destination_port: 1194
    #     jump: ACCEPT
    #     rule_num: 4

    # - name: Iptables flush filter
    #   ansible.builtin.iptables:
    #     chain: "{{ item }}"
    #     flush: yes
    #   loop:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]
  
  post_tasks:

    - name: Add iptables rule
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: 1194
        jump: ACCEPT
        action: insert
        rule_num: 4
    
    # - name: Delete Oracle firewall FORWARD rules
    #   command: iptables -F FORWARD

    # - name: Delete Oracle firewall INPUT rule
    #   command: iptables -t filter -D INPUT 5

    - name: Save iptables
      shell: iptables-save > /etc/sysconfig/iptables

  roles:
    - role: kyl191.openvpn
      clients:
        - rand-pc
        - rand-netbook
        # - rand-phone
        # - rand-work
        # - client1
        # - client2
        # - client3
        # - client4
        # - client5
