---
- hosts: all
  gather_facts: true
  become: yes

  post_tasks:

    - name: Delete default reject rule
      lineinfile: 
        dest: /etc/firewalld/direct.xml 
        state: absent 
        regexp: "{{ item }}"
      loop: 
       - ".*-A INPUT -j REJECT --reject-with icmp-host-prohibited.*"
       - ".*-A FORWARD -j REJECT --reject-with icmp-host-prohibited.*"
      register: default_rule_clean


    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
      when: default_rule_clean.changed

  roles:
    - role: kyl191.openvpn
      clients:
        - rand-pc
        #- rand-netbook
        # - rand-phone
        # - rand-work
        # - client1
        # - client2
        # - client3
        # - client4
        # - client5
